#! /bin/sh

# Roman's
#   _                                 
#  | |__  ___ _ ____      ___ __ ___  
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#             |_|                      

pgrep -x sxhkd > /dev/null || sxhkd &

# Set up workspaces (1-X)
bspc monitor eDP-1 -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set up displays
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 165 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate left --left-of DisplayPort-2

# Keep Discord on Workspace 4
bspc rule -a discord desktop="^4"

#Autostart applications
sxhkd &
polybar top &
kitty -e zsh -c "neofetch; exec zsh" &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
dunst &
flameshot &
solaar --window=hide &
